# Start VMs on openstack
- hosts: localhost
  become: no
  roles:
    - role: os-cluster
  tags:
    - openstack

# Install python2.7 if needed
- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: install python 2
      raw: (test -e /usr/bin/python && /usr/bin/python -V 2>&1 | grep -q 'Python 2.7') || (apt -y update && apt install -y python-minimal)
      changed_when: no
  tags:
    - predeploy

# Base configuration
- hosts: all
  tasks:
    - name: Ensure hostname is present in /etc/hosts
      become: yes
      lineinfile:
        dest=/etc/hosts
        line='127.0.1.1 {{ ansible_hostname }}'
        regexp='^127\.0\.1\.1'
        insertafter='^127\.0\.0\.1'
        state=present

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
      when: upgrade_os == True

    - name: Reboot system if required
      become: true
      shell: sleep 5 && shutdown -r now 'Rebooting to complete system upgrade'
      args:
        removes: /var/run/reboot-required
      async: 300
      poll: 0
      ignore_errors: true
      # register: rebooted

    - name: Wait for the system to become reachable again
      wait_for_connection:
        delay: 60
        timeout: 300

  tags:
    - predeploy