apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  labels:
    # insert any desired labels to identify your claim
    app: mypvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # The amount of the volume's storage to request
      storage: 2Gi
